name: fs-video-transcriber
services:
  web:
    container_name: go-react-video-transcriber-web
    image: go-react-video-transcriber-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.local
    ports:
      - 3000:3000    
  api:
    container_name: go-react-video-transcriber-api
    image: go-react-video-transcriber-api
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.local
    ports:
      - 4000:4000